baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
<section>
<ol>
  <li><a href="https://github.com" target="_blank">GitHub</a></li>
  <li><a href="https://google.com" target="_blank">Google</a></li>
  <li><a href="https://stackoverflow.com" target="_blank">Stack Overflow</a></li>
  <li><a href="https://chat.openai.com" target="_blank">ChatGPT</a></li>
  <li><a href="https://mail.google.com" target="_blank">Gmail</a></li>
</ol>
</section>